# API version
apiVersion: v1

# ConfigMap = stores non-sensitive config data
kind: ConfigMap

# Info about this configmap
metadata:
  # Name of this configmap
  name: cyber-app-config
  # Namespace for production
  namespace: cyber-prod-env

# Key-value pairs
# Note: these are plain text, not encoded
data:

  # Hostname of the Postgres service
  DB_HOST: "postgres-service"
  # Port for Postgres
  DB_PORT: "5432"

  # Hostname of the Redis service
  REDIS_HOST: "redis-service"
  # Port for Redis
  REDIS_PORT: "6379"
  # Turn off debug in production
  DJANGO_DEBUG: "False"
  # Which domains are allowed to connect
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,ali-devsecops.local"
