# API version
apiVersion: v1
# PersistentVolumeClaim = ask Kubernetes for disk space
kind: PersistentVolumeClaim

# Info about this claim
metadata:
  # Name of this storage claim
  name: pvc-postgres
  # Namespace for production
  namespace: cyber-prod-env

# What kind of storage we need
spec:
  # ReadWriteOnce = one pod can read/write
  accessModes:
    - ReadWriteOnce
  # How much space
  resources:
    requests:
      # 1 Gigabyte
      storage: 1Gi
