# Configure Nginx as a Reverse Proxy for Django Gunicorn

server {

  # Listen to standard web traffic on port 80 (HTTP)
  listen 80;

  # Define the domain name or host name for this server configuration
  server_name localhost;

  # Handle Static Files directly via Nginx for maximum performance
  location /static/ {
 
     # Point to the actual folder inside the container where static files are saved
     alias /app/staticfiles/;

  }

  # Pass all dynamic web requests to the secure Django container
  location / {

    # Forward the traffic to the Django service using its container name and internal port
    proxy_pass http://ali-devsecops-app:8000;

    # Send the real IP address of the visiting user to Django code
    proxy_set_header X-Real-IP $remote_addr;

    # Keep track of the proxy chain IPs to help Django identify the correct traffic origin
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Tell Django if the original request used HTTP or HTTPS protocol
    proxy_set_header X-Forwarded-Proto $scheme;
    }
}
