# Configure Nginx as a Reverse Proxy for Django Gunicorn

server {

  # Listen on port 80 for HTTP requests
  listen 80;

  # Define server name (domain or localhost)
  server_name localhost;

  # Handle static files (CSS, JS, images) directly
  location /static/ {

     # Path inside container where static files exist
     alias /app/staticfiles/;

  }

  # Handle all other requests (dynamic requests)
  location / {

    # Send request to Django app container (Gunicorn)
    proxy_pass http://ali-devsecops-app:8000;

    # Send real client IP to backend
    proxy_set_header X-Real-IP $remote_addr;

    # Send full chain of client IPs (important for logs)
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Tell backend if request is HTTP or HTTPS
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
