apiVersion: v1
kind: Namespace # Resource type

metadata:
  name: velero

---

apiVersion: v1
kind: Service

metadata:
  name: minio
  namespace: velero

spec:
  selector:
    app: minio # Send traffic to Pods with app=minio

  ports:

    # Expose API on port 9000
    - name: api
      port: 9000
      targetPort: 9000 # Forward traffic to container port 9000

    # Expose Web Console on port 9001
    - name: console
      port: 9001
      targetPort: 9001 # Forward traffic to container port 9001

---

# MinIO Deployment

apiVersion: apps/v1
kind: Deployment

metadata:
  name: minio
  namespace: velero

spec:
  selector:
    matchLabels:
      app: minio # Select Pods with app=minio

  strategy:
    type: Recreate # Delete old Pod before creating new one

  template:
    metadata:
      labels:
        app: minio # Label added to the Pod

    spec:
      containers:

        # Container configuration
        - image: minio/minio:latest
          name: minio

          env:

            # Where MinIO stores its data
            - name: MINIO_DATA_PATH
              value: "/data"

            # Web Console address (port 9001)
            - name: MINIO_CONSOLE_ADDRESS
              value: ":9001"

            # Root user (matches cyber-app-secrets value)
            - name: MINIO_ROOT_USER
              value: "minio"

            # Root password (matches cyber-app-secrets value)
            - name: MINIO_ROOT_PASSWORD
              value: "minio123"

          # Run shell & Create storage folder then start MinIO
          command:
            - sh
            - -c
            - |
              mkdir -p ${MINIO_DATA_PATH}/velero
              minio server ${MINIO_DATA_PATH} --console-address "${MINIO_CONSOLE_ADDRESS}"

          ports:

            # MinIO API port
            - name: api
              containerPort: 9000

            # MinIO Web Console port
            - name: console
              containerPort: 9001
