apiVersion: velero.io/v1

kind: Schedule

metadata:
  name: daily-app-backup
  namespace: velero


# Specification for backup schedule
spec:

  # Cron expression: run daily at 2 AM
  schedule: "0 2 * * *"

# Template for the backup task
  template:

    # target namespaces to BACKUP
    includedNamespaces:
      - cyber-prod-env

    # TimeToLeve: keep backup for 7D
    ttl: 168h0m0s
     # Take snapshots of attached persistent volumes
    snapshotVolumes: true

